---
.travis.yml:
  secure_global_env:
    # PUBLISHER_PASSWORD
    - "QnxL/++ocXhHHkwLvuVBKi5GFqEIQfiun6mOYZK6IygSr5edtzs4Lp20rLiJqIJ2w6GDq0W3CO/ulKslAUvVLP7Vz5Ezx6+Pb/y/SJi3BN9mPLO+544Jv3iRnZLArNT6Y61FHSt1yUOgvk01rzcmAfVq9TDa+QARWDXRroypOP8="
