---
language: ruby
sudo: false
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'", "bundle exec rake metadata"]
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  allow_failures:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "eIYe0apMriqXchX+7ha3UCxKOssQkVfiYL0N4kfbf3+UtH3HC3Z8v/dD6eUD+QJDHDYwj0SKtrsQueuwJdA4lQWowIV8IacL4CJqvfsP7lNYvSotHlb19p4442cJNghIUmCcOGdqTBSkxoGffJCGM3jE4gT1gWHoECq1f1igvTE="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
